# Generated by Django 4.0.5 on 2022-11-22 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=500)),
                ('author', models.CharField(max_length=100)),
                ('like_count', models.PositiveIntegerField(default=0)),
                ('pub_date', models.DateTimeField()),
            ],
        ),
    ]
