# Generated by Django 4.1 on 2023-01-04 07:27

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import smarang_back_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('nickname', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', smarang_back_app.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AuthSMS',
            fields=[
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('phone_number', models.CharField(max_length=16, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')])),
                ('auth_number', models.IntegerField(verbose_name='인증 번호')),
                ('auth_pass', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'authsms',
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(blank=True, max_length=50, null=True)),
                ('brand_addr', models.CharField(max_length=50)),
                ('brand_date', models.CharField(max_length=50)),
                ('brand_scale', models.CharField(max_length=50)),
                ('brand_shape', models.CharField(max_length=50)),
                ('brand_price', models.CharField(max_length=50)),
                ('brand_profit', models.CharField(max_length=50)),
                ('brand_profit_loss', models.CharField(max_length=50)),
                ('brand_credit_grade', models.CharField(max_length=50)),
                ('brand_credit_grade_score', models.CharField(max_length=50)),
                ('brand_employees', models.CharField(max_length=50)),
                ('brand_industry', models.CharField(max_length=50)),
                ('brand_Needs', models.CharField(max_length=50)),
                ('brand_grade', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Marketer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marketer_age', models.CharField(max_length=50)),
                ('marketer_addr', models.CharField(max_length=50)),
                ('marketer_job', models.CharField(max_length=50)),
                ('marketer_career', models.CharField(max_length=50)),
                ('marketer_form', models.CharField(max_length=50)),
                ('marketer_plat', models.CharField(max_length=50)),
                ('marketer_pow', models.CharField(max_length=50)),
                ('marketer_grade', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marketer_age', models.CharField(max_length=50)),
                ('marketer_addr', models.CharField(max_length=50)),
                ('marketer_job', models.CharField(max_length=50)),
                ('marketer_career', models.CharField(max_length=50)),
                ('marketer_form', models.CharField(max_length=50)),
                ('marketer_plat', models.CharField(max_length=50)),
                ('marketer_pow', models.CharField(max_length=50)),
                ('marketer_grade', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Marketer_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phoneNumber', models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')])),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_m', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Brand_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phoneNumber', models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')])),
                ('buisnessNumber', models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')])),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_b', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
