# Generated by Django 4.0.5 on 2022-11-22 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smarang_back_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Board',
        ),
    ]
