# Generated by Django 4.1 on 2023-01-13 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smarang_back_app', '0002_items_item_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perform_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_id_perform', to='smarang_back_app.items')),
            ],
        ),
        migrations.CreateModel(
            name='Perform_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('data', models.CharField(max_length=50)),
                ('Item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perform_id', to='smarang_back_app.perform_data')),
            ],
        ),
    ]
