# Generated by Django 4.1 on 2023-01-13 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smarang_back_app', '0003_perform_data_perform_list'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perform_data',
            old_name='Item_id',
            new_name='Item_id_per',
        ),
    ]
