# Generated by Django 4.1 on 2023-01-13 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smarang_back_app', '0004_rename_item_id_perform_data_item_id_per'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perform_list',
            old_name='Item_id',
            new_name='Perform_id',
        ),
    ]
