# Generated by Django 4.1 on 2022-12-15 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smarang_back_app', '0004_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
