# Generated by Django 4.1 on 2022-12-15 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smarang_back_app', '0005_delete_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marketer_age', models.CharField(max_length=50)),
                ('marketer_addr', models.CharField(max_length=50)),
                ('marketer_job', models.CharField(max_length=50)),
                ('marketer_career', models.CharField(max_length=50)),
                ('marketer_form', models.CharField(max_length=50)),
                ('marketer_plat', models.CharField(max_length=50)),
                ('marketer_pow', models.CharField(max_length=50)),
                ('marketer_grade', models.CharField(max_length=50)),
            ],
        ),
    ]
