# Generated by Django 4.1 on 2023-01-13 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smarang_back_app', '0005_rename_item_id_perform_list_perform_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perform_data',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
