# Generated by Django 4.1 on 2023-01-13 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smarang_back_app', '0006_alter_perform_data_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perform_data',
            name='created_at',
        ),
    ]
