# Generated by Django 4.1 on 2023-01-15 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smarang_back_app', '0008_perform_data_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perform_list',
            name='data',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
