# Generated by Django 4.1 on 2023-01-15 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smarang_back_app', '0009_alter_perform_list_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='perform_data',
            name='Marketer_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Marketer_user', to='smarang_back_app.marketer'),
            preserve_default=False,
        ),
    ]
