# Generated by Django 4.1 on 2023-01-15 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smarang_back_app', '0010_perform_data_marketer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perform_data',
            name='Marketer_user',
        ),
        migrations.AddField(
            model_name='perform_data',
            name='Marketer_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Marketer_user', to='smarang_back_app.marketer_user'),
            preserve_default=False,
        ),
    ]
