# Generated by Django 4.1 on 2023-01-15 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smarang_back_app', '0011_remove_perform_data_marketer_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authsms',
            name='auth_pass',
        ),
    ]
