# Generated by Django 4.1 on 2023-01-16 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smarang_back_app', '0013_item_succ_items_brand_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_succ',
            name='Item_id_per',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='item_id_perform_succ', to='smarang_back_app.items'),
            preserve_default=False,
        ),
    ]
