# Generated by Django 4.1 on 2023-01-16 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smarang_back_app', '0014_item_succ_item_id_per'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_succ',
            name='Marketer_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Marketer_user_succ', to='smarang_back_app.marketer_user'),
            preserve_default=False,
        ),
    ]
