# Generated by Django 4.1 on 2023-01-17 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smarang_back_app', '0015_item_succ_marketer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_succ',
            name='Item_title',
            field=models.CharField(max_length=50),
        ),
    ]
