# Generated by Django 4.1 on 2023-01-17 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smarang_back_app', '0019_user_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cal_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cal_title', models.CharField(max_length=50)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('described', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Cal_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_id_cal', to='smarang_back_app.items')),
            ],
        ),
    ]
