# Generated by Django 4.1 on 2023-01-17 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smarang_back_app', '0020_cal_data_cal_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='cal_data',
            name='cal_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cal_id', to='smarang_back_app.cal_table'),
            preserve_default=False,
        ),
    ]
