# Generated by Django 4.1 on 2023-01-17 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smarang_back_app', '0022_alter_cal_data_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cal_data',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
