# Generated by Django 4.1 on 2023-01-17 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smarang_back_app', '0024_alter_cal_data_date_joined'),
    ]

    operations = [
        migrations.CreateModel(
            name='Button_con',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='item_list',
            name='memo',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='UploadFileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='')),
                ('file', models.FileField(null=True, upload_to='')),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_id_file', to='smarang_back_app.item_list')),
            ],
        ),
        migrations.CreateModel(
            name='Button_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('button_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='button_con_id', to='smarang_back_app.button_con')),
            ],
        ),
        migrations.AddField(
            model_name='button_con',
            name='item_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_id_btn', to='smarang_back_app.item_list'),
        ),
    ]
