# Generated by Django 4.1 on 2023-01-17 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smarang_back_app', '0025_button_con_item_list_memo_uploadfilemodel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='button_con',
            name='item_id',
        ),
        migrations.RemoveField(
            model_name='item_list',
            name='memo',
        ),
        migrations.RemoveField(
            model_name='uploadfilemodel',
            name='item_id',
        ),
        migrations.AddField(
            model_name='button_con',
            name='perform_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='perform_id_btn', to='smarang_back_app.perform_data'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perform_data',
            name='memo',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uploadfilemodel',
            name='perform_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='perform_id_file', to='smarang_back_app.perform_data'),
            preserve_default=False,
        ),
    ]
