# Generated by Django 4.1 on 2023-01-17 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smarang_back_app', '0026_remove_button_con_item_id_remove_item_list_memo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='button_status',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='perform_data',
            name='memo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='uploadfilemodel',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
