# Generated by Django 4.1 on 2023-01-18 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smarang_back_app', '0027_alter_button_status_color_alter_perform_data_memo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='button_con',
            name='memo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
