# Generated by Django 4.1 on 2023-01-18 02:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smarang_back_app', '0029_button_con_button_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand_user',
            name='phoneNumber',
            field=models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')]),
        ),
        migrations.AlterField(
            model_name='marketer_user',
            name='phoneNumber',
            field=models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')]),
        ),
    ]
