# Generated by Django 4.1 on 2023-01-24 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smarang_back_app', '0031_button_status_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='cal_data',
            name='perform',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='per', to='smarang_back_app.perform_data'),
            preserve_default=False,
        ),
    ]
