# Generated by Django 4.1 on 2023-01-24 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smarang_back_app', '0035_perform_data_cal_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perform_data',
            name='cal_id',
        ),
    ]
