# Generated by Django 4.1 on 2023-01-25 15:35

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smarang_back_app', '0040_notice'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='description',
            field=ckeditor.fields.RichTextField(default=1),
            preserve_default=False,
        ),
    ]
