# Generated by Django 4.1 on 2023-01-25 15:47

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smarang_back_app', '0041_notice_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
