# Generated by Django 4.1 on 2023-01-26 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smarang_back_app', '0043_terms'),
    ]

    operations = [
        migrations.AddField(
            model_name='terms',
            name='eventKey',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
