# Generated by Django 4.1 on 2023-01-28 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smarang_back_app', '0044_terms_eventkey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perform_data',
            name='cal_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cal_id_perform', to='smarang_back_app.cal_data'),
        ),
    ]
