# Generated by Django 4.1 on 2023-02-08 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smarang_back_app', '0045_alter_perform_data_cal_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marketer_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marketer_age', models.CharField(max_length=50)),
                ('marketer_addr', models.CharField(max_length=50)),
                ('marketer_job', models.CharField(max_length=50)),
                ('marketer_career', models.CharField(max_length=50)),
                ('marketer_form', models.CharField(max_length=50)),
                ('marketer_plat', models.CharField(max_length=50)),
                ('marketer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketer_u', to='smarang_back_app.marketer_user')),
            ],
        ),
        migrations.CreateModel(
            name='Brand_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(blank=True, max_length=50, null=True)),
                ('brand_addr', models.CharField(max_length=50)),
                ('brand_date', models.CharField(max_length=50)),
                ('brand_price', models.CharField(max_length=50)),
                ('brand_profit', models.CharField(max_length=50)),
                ('brand_credit_grade_score', models.CharField(max_length=50)),
                ('brand_employees', models.CharField(max_length=50)),
                ('brand_industry', models.CharField(max_length=50)),
                ('brand_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_u', to='smarang_back_app.brand_user')),
            ],
        ),
    ]
