# Generated by Django 4.1 on 2023-02-08 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smarang_back_app', '0046_marketer_detail_brand_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketer_detail',
            name='marketer_addr',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='marketer_detail',
            name='marketer_age',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='marketer_detail',
            name='marketer_career',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='marketer_detail',
            name='marketer_form',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='marketer_detail',
            name='marketer_job',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='marketer_detail',
            name='marketer_plat',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
