# Generated by Django 4.1 on 2023-02-09 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smarang_back_app', '0049_brand_raw_brand_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='modified_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
