# Generated by Django 4.1 on 2023-02-09 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smarang_back_app', '0050_brand_modified_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='modified_time',
            new_name='updated_time',
        ),
    ]
