# Generated by Django 4.1 on 2023-02-09 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smarang_back_app', '0051_rename_modified_time_brand_updated_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='updated_time',
            field=models.DateField(auto_now=True),
        ),
    ]
