# Generated by Django 4.1 on 2023-02-09 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smarang_back_app', '0052_alter_brand_updated_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='ver_id',
            field=models.IntegerField(default=-1),
        ),
    ]
