# Generated by Django 4.1 on 2023-02-09 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smarang_back_app', '0053_brand_ver_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ai_version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ver_name', models.CharField(max_length=50)),
                ('ver_id', models.IntegerField()),
                ('updated_time', models.DateField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='brand_status',
            name='brand_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_id_d', to='smarang_back_app.brand_raw'),
        ),
        migrations.CreateModel(
            name='Brand_dummy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_id', to='smarang_back_app.brand_raw')),
            ],
        ),
    ]
