# Generated by Django 4.1 on 2023-02-09 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smarang_back_app', '0054_ai_version_alter_brand_status_brand_id_brand_dummy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand_back_up',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(blank=True, max_length=50, null=True)),
                ('brand_addr', models.CharField(max_length=50)),
                ('brand_date', models.CharField(max_length=50)),
                ('brand_scale', models.CharField(max_length=50)),
                ('brand_shape', models.CharField(max_length=50)),
                ('brand_price', models.CharField(max_length=50)),
                ('brand_profit', models.CharField(max_length=50)),
                ('brand_profit_loss', models.CharField(max_length=50)),
                ('brand_credit_grade', models.CharField(max_length=50)),
                ('brand_credit_grade_score', models.CharField(max_length=50)),
                ('brand_employees', models.CharField(max_length=50)),
                ('brand_industry', models.CharField(max_length=50)),
                ('brand_Needs', models.CharField(max_length=50)),
                ('brand_grade', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
