# Generated by Django 4.1 on 2023-02-09 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smarang_back_app', '0055_brand_back_up'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='updated_time',
            field=models.DateField(),
        ),
    ]
